version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: shinodalabs
      POSTGRES_PASSWORD: shinodalabs
      POSTGRES_DB: financeAI
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - financeAINetwork

networks:
  financeAINetwork:
    driver: bridge

volumes:
  pgdata:
